"use strict";

module.exports = Object.freeze({

    /** Application States */
    STATES: {
        STARTMODE: '_STARTMODE',
        SETUPMODE: '_SETUPMODE'
    },

    /** Session context for ADVANCED State Management */
    CONTEXT: {
        /** New Session & Setup */
        NEW_SESSION: 'NEW_SESSION',
        DEVICE_SETUP: 'DEVICE_SETUP',
        VERIFY_ZIPCODE: 'VERIFY_ZIPCODE',
        VERIFY_ZIPCODE_NO: 'VERIFY_ZIPCODE_NO',
        VERIFY_ZIPCODE_YES: 'VERIFY_ZIPCODE_YES',
        UNKNOWN_REQUEST: "UNKNOWN_REQUEST",
        START_LAUNCH_REQUEST: "START_LAUNCH_REQUEST",
        SETUP_LAUNCH_REQUEST: "SETUP_LAUNCH_REQUEST",
        DIRECT_INTENT_REQUEST: "DIRECT_INTENT_REQUEST",
        INVALID_ZIPCODE_RESPONSE: "INVALID_ZIPCODE_RESPONSE",
        INVALID_STOP_ID_RESPONSE: "INVALID_STOP_ID_RESPONSE",
        GENERAL_HELP: "GENERAL_HELP",
        NO_GEOCODE_FOUND: "NO_GEOCODE_FOUND",
        NO_TIMEZONE_FOUND: "NO_TIMEZONE_FOUND",
        VERIFY_LOCATION: "VERIFY_LOCATION",
        VERIFY_LOCATION_YES: "VERIFY_LOCATION_YES",
        VERIFY_LOCATION_NO: "VERIFY_LOCATION_NO",
        SERVICE_NOT_AVAILABLE: "SERVICE_NOT_AVAILABLE",
        PROVIDER_CODE_NOT_FOUND: "PROVIDER_CODE_NOT_FOUND",
        STOPS_FOUND: "STOPS_FOUND",
        VERIFY_STOP: "VERIFY_STOP",
        VERIFY_STOP_YES: "VERIFY_STOP_YES",
        VERIFY_STOP_NO: "VERIFY_STOP_NO",
        NO_STOPS_FOUND: "NO_STOPS_FOUND",
        MOVE_NEXT: "MOVE_NEXT",
        MOVE_PREVIOUS: "MOVE_PREVIOUS",
        LAST_STOP_INDEX: "LAST_STOP_INDEX",
        FIRST_STOP_INDEX: "FIRST_STOP_INDEX",
        STOP_ID_SETUP: "STOP_ID_SETUP",
        ZIPCODE_SETUP: "ZIPCODE_SETUP",
        VERIFY_STOP_ID_SETUP: "VERIFY_STOP_ID_SETUP",
        VERIFY_STOP_ID_SETUP_YES: "VERIFY_STOP_ID_SETUP_YES",
        VERIFY_STOP_ID_SETUP_NO: "VERIFY_STOP_ID_SETUP_NO",
        NO_COUNTRY_FOUND: "NO_COUNTRY_FOUND",
        COUNTRY_FOUND: "COUNTRY_FOUND",
        VERIFY_COUNTRY: "VERIFY_COUNTRY",
        VERIFY_COUNTRY_YES: "VERIFY_COUNTRY_YES",
        VERIFY_COUNTRY_NO: "VERIFY_COUNTRY_NO",
        VERIFY_STOP_DETAILS: "VERIFY_STOP_DETAILS",
        VERIFY_STOP_DETAILS_YES: "VERIFY_STOP_DETAILS_YES",
        VERIFY_STOP_DETAILS_NO: "VERIFY_STOP_DETAILS_NO",
        ZIPCODE_TIMZONE_FOUND: "ZIPCODE_TIMZONE_FOUND",
        TIMEZONE_NOT_FOUND: "TIMEZONE_NOT_FOUND",
        GEOCODE_NOT_FOUND: "GEOCODE_NOT_FOUND",
        /** STARTMODE */
        WELCOME: "WELCOME",
        GET_HOME_BRIEFING: "GET_HOME_BRIEFING",
        GET_HOME_BRIEFING_NO: "GET_HOME_BRIEFING_NO",
        GET_HOME_BRIEFING_YES: "GET_HOME_BRIEFING_YES",
        GET_MORE_SUMMARY: "GET_MORE_SUMMARY",
        GET_MORE_SUMMARY_YES: "GET_MORE_SUMMARY_YES",
        GET_MORE_SUMMARY_NO: "GET_MORE_SUMMARY_NO",
        HOME_ARRIVALS: "HOME_ARRIVALS",
        GET_ARRIVALS: "GET_ARRIVALS",
        GET_ARRIVALS_YES: "GET_ARRIVALS_YES",
        GET_ARRIVALS_NO: "GET_ARRIVALS_NO",
        GET_ANOTHER_ARRIVAL: "GET_ANOTHER_ARRIVAL",
        GET_ANOTHER_ARRIVAL_YES: "GET_ANOTHER_ARRIVAL_YES",
        GET_ANOTHER_ARRIVAL_NO: "GET_ANOTHER_ARRIVAL_NO",
        HOME_ALERTS: "HOME_ALERTS",
        GET_ALERTS: "GET_ALERTS",
        GET_ALERTS_YES: "GET_ALERTS_YES",
        GET_ALERTS_NO: "GET_ALERTS_NO",
        HOME_SCHEDULES: "HOME_SCHEDULES",
        GET_SCHEDULES: "GET_SCHEDULES",
        GET_SCHEDULES_YES: "GET_SCHEDULES_YES",
        GET_SCHEDULES_NO: "GET_SCHEDULES_NO",
        HOME_DELAYS: "HOME_DELAYS",
        GET_DELAYS: "GET_DELAYS",
        GET_DELAYS_YES: "GET_DELAYS_YES",
        GET_DELAYS_NO: "GET_DELAYS_NO",
        HOME_DETOURES: "HOME_DETOURES",
        GET_DETOURES: "GET_DETOURES",
        GET_DETOURES_YES: "GET_DETOURES_YES",
        GET_DETOURES_NO: "GET_DETOURES_NO",
        INVALID_STOP_ID: "INVALID_STOP_ID",
        INVALID_BUS_ID: "INVALID_BUS_ID",
        INVALID_ROUTE_ID: "INVALID_ROUTE_ID",
        GET_SUMMARY: "GET_SUMMARY",
        GET_SUMMARY_YES: "GET_SUMMARY_YES",
        GET_SUMMARY_NO: "GET_SUMMARY_NO",
        VERIFY_STOP_ID: "VERIFTY_STOP_ID",
        VERIFY_BUS_ID: "VERIFY_BUS_ID",
        VERIFY_ROUTE_ID: "VERIFY_ROUTE_ID",
        REQUEST_MORE: "REQUEST_MORE",
        GET_STOP_BRIEFING: "GET_STOP_BRIEFING",
        GET_STOP_BRIEFING_YES: "GET_STOP_BRIEFING_YES",
        GET_STOP_BRIEFING_NO: "GET_STOP_BRIEFING_NO",
        GET_STOP_BRIEFING_END: "GET_STOP_BRIEFING_END",
        GET_STOP_ARRIVALS: "GET_STOP_ARRIVALS",
        GET_STOP_ARRIVALS_YES: "GET_STOP_ARRIVALS_YES",
        GET_STOP_ARRIVALS_NO: "GET_STOP_ARRIVALS_NO",
        GET_STOP_SCHEDULES: "GET_STOP_SCHEDULES",
        GET_STOP_SCHEDULES_YES: "GET_STOP_SCHEDULES_YES",
        GET_STOP_SCHEDULES_NO: "GET_STOP_SCHEDULES_NO",
        GET_STOP_ALERTS: "GET_STOP_ALERTS",
        GET_STOP_ALERTS_YES: "GET_STOP_ALERTS_YES",
        GET_STOP_ALERTS_NO: "GET_STOP_ALERTS_NO",
        GET_STOP_DELAYS: "GET_STOP_DELAYS",
        GET_STOP_DELAYS_YES: "GET_STOP_DELAYS_YES",
        GET_STOP_DELAYS_NO: "GET_STOP_DELAYS_NO",
        GET_ROUTE_DETOURS: "GET_ROUTE_DETOURS",
        GET_ROUTE_DETOURS_YES: "GET_ROUTE_DETOURS_YES",
        GET_ROUTE_DETOURS_NO: "GET_ROUTE_DETOURS_NO",
        VERIFY_STATION_DETAILS: "VERIFY_STATION_DETAILS",
        VERIFY_STATION_DETAILS_YES: "VERIFY_STATION_DETAILS_YES",
        VERIFY_STATION_DETAILS_NO: "VERIFY_STATION_DETAILS_NO",
        VERIFY_STATION: "VERIFY_STATION",
        VERIFY_STATION_YES: "VERIFY_STATION_YES",
        VERIFY_STATION_NO: "VERIFY_STATION_NO",
        GET_AGENCY: "GET_AGENCY",
        GET_AGENCY_YES: "GET_AGENCY_YES",
        GET_AGENCY_NO: "GET_AGENCY_NO",
        VERIFY_AGENCY: "VERIFY_AGENCY",
        VERIFY_AGENCY_YES: "VERIFY_AGENCY_YES",
        VERIFY_AGENCY_NO: "VERIFY_AGENCY_NO",
        NEXT_ITEM: "NEXT_ITEM",
        PREVIOUS_ITEM: "PREVIOUS_ITEM",
        LAST_ITEM_INDEX: "LAST_ITEM_INDEX",
        FIRST_ITEM_INDEX: "FIRST_ITEM_INDEX",
        ASK_OR_EXIT: "ASK_OR_EXIT",
        CURRENT_REQUEST : "CURRENT_REQUEST"
    },

    /** Speech Pauses */
    BREAKTIME: {
        '50': '<break time = "50ms"/>',
        '100': '<break time = "100ms"/>',
        '150': '<break time = "150ms"/>',
        '200': '<break time = "200ms"/>',
        '250': '<break time = "250ms"/>',
        '300': '<break time = "300ms"/>',
        '350': '<break time = "350ms"/>',
        '400': '<break time = "400ms"/>',
        '500': '<break time = "500ms"/>',
        'SENTENCE': '<break strength="strong"/>',
        'PARAGRAPH': '<break strength="x-strong"/>'
    },


    /** API */
    API: {
        PARAMS: {
            APP_KEY: "APP_KEY",
            STOP_DISTANCE: "STOP_DISTANCE"
        },
        TYPE: {
            STOPS: "STOPS",
            STOP_DETAILS: "STOP_DETAILS",
            STATIONS: "STATIONS",
            STATION_DETAILS: "STATION_DETAILS",
            ROUTES: "ROUTES",
            ARRIVALS: "ARRIVALS",
            DELAYS: "DELAYS",
            SCHEDULES: "SCHEDULES",
            DETOURES: "DETOURES",
            ALERTS: "ALERTS",
            GEOCODE: "GEOCODE",
            TIMEZONE: "TIMEZONE",
            QUOTES: "QUOTES",
            PLACES: "PLACES",
            SERVING_AGENCIES: "SERVING_AGENCIES",
            BUSES: "BUSES",
            BUSES_DETAILS: "BUSES_DETAILS",
            VEHICLES: "VEHICLES",
            VEHICLES_DETAILS: "VEHICLES_DETAILS",
            TRAINS: "TRAINS",
            TRAINS_DETAILS: "TRAINS_DETAILS"
        },
        RESPONSE: {
            SUMMARY: "SUMMARY",
            BRIEFING: "BRIEFING",
            FLASH: "FLASH",
            ALERTS: "ALERTS",
            SERVICE_ALERTS: "SERVICE_ALERTS",
            ARRIVALS: "ARRIVALS",
            SCHEDULES: "SCHEDULES",
            DETOURES: "DETOURES",
            STOPS: "STOPS",
            DELAYS: "DELAYS",
            ROUTES: "ROUTES",
            PLATFORMS: "PLATFORMS"
        },
        PARAMETERS: {
            /** TRIMET */
            STOP_ID: "stopId",
            ROUTE_ID: "routeId",
            LATITUDE: "lat",
            LONGIUDE: "lng",
            APP_KEY: "APP_KEY",
            STOP_DISTANCE: "STOP_DISTANCE",
            /** BART */
            BART: {
                COMMAND: "cmd",
                KEY: "key",
                DESTINATION: "dest",
                ARRIVAL_TIME: "time",
                TRIPS_BEFORE: "b",
                TRIPS_AFTER: "a",
                SHOW_LEGEND: "l",
                DATE: "date",
                ROUTE: "route",
                SCHEDULE: "sched",
                PLATFORM: "plat",
                DIRECTION: "dir",
                ORIGIN: "orig"
            },
            OBA: {
                LATITUDE: "lat",
                LONGIUDE: "lon",
                LATITUDE_SPAN: "latSpan",
                LONGITUDE_SPAN: "lonSpan",
                KEY: "key",
                RADIUS: "radius",
                QUERY: "query",
                DATE: "date",
                TIME: "time",
                INCLUDE_TRIP: "includeTrip",
                INCLUDE_SCHEDULE: "includeSchedule",
                INCLUDE_STATUS: "includeStatus",
                CALLBACK_URL: "url",
                ON_ARRIVAL: "onArrival",
                ALARM_TIME_OFFSET: "alarmTimeOffset",
                AGENCY_ID: "agencyId",
                SERVICE_DATE: "serviceDate",
                STOP_ID: "stopId",
                ROUTE_ID: "routeId"
            },
            CTA: {
                /** Common Parameters */
                KEY: "key",
                VERSION: "version",
                LOCALE: "locale",
                FORMAT: "format",
                OUTPUT_TYPE: "outputType",
                TYPE: "type",
                ROUTE_ID: "routeid",
                STATION_ID: "stationid",
                ACTIVE_ONLY: "activeonly",
                ACCESSIBILITY: "accessibility",
                PLANNED: "planned",
                BY_START_DATE: "bystartdate",
                RECENT_DAYS: "recentdays",
                MAP_ID: "mapid",
                MAXIMUM_RESULTS: "max",
                ROUTE_CODE: "rt",
                RUN_NUMBER: "runnumber",
                VEHICLE_ID: "Vid",
                ROUTES: "Rt",
                TIMESTAMP_RESOLUTION: "tmres",
                SMALL_ROUTES: "rt",
                DIRECTION: "dir",
                PATTERN_ID: "pid",
                STOP_ID_SMALL: "stpid",
                TOP: "top",
                ROUTE_DIRECTION: "Rtdir",
                STOP_ID_BIG: "Stpid"
            }
        },
        PROPERTIES: {
            STATUS: "status",
            LOCATION: "location",
            LATITUDE: "lat",
            LONGIUDE: "lng",
            IS_DELAYED: "delayed",
            DELAY_MINUTES: "delayMins",
            TRANSIT_STATUS : "transitStatus",
            GEOCODE: {
                CITY: "locality",
                SUB_CITY: "sublocality",
                STATE: "administrative_area_level_1",
                COUNTY: "administrative_area_level_2",
                LONG_NAME: "long_name",
                SHORT_NAME: "short_name",
                COUNTRY: "country",
                PLACE_ID: "place_id",
                TYPES: "types",
                POSTAL_CODE: "postal_code",
                RESULT_SET: "results",
                ADDRESS_COMPONENT: "address_components",
                GEOMETRY: "geometry"
            },
            TIMEZONE: {
                DATA_OFFSET: "dstOffset",
                RAW_OFFSET: "rawOffset",
                TIMEZONE_ID: "timeZoneId",
                TIMEZONE_NAME: "timeZoneName",
                RESULT_SET: "results"
            },
            PLACES: {
                RESULT_SET: "predictions",
                DESCRIPTION: "description"
            },
            TRIMET: {
                DETOUR: "detour",
                ROUTE: "route",
                TYPE: "type",
                DESCRIPTION: "desc",
                END: "end",
                INFO_LINK_URL: "info_link_url",
                ID: "id",
                BEGIN: "begin",
                ARRIVAL: "arrival",
                FEET: "feet",
                IN_CONGESTION: "inCongestion",
                DEPARTED: "departed",
                SCHEDULED: "scheduled",
                LOAD_PERCENTAGE: "loadPercentage",
                SHORT_SIGN: "shortSign",
                ESTIMATED: "estimated",
                DETOURED: "detoured",
                TRIP_ID: "tripID",
                DIRECTION: "dir",
                BLOCK_ID: "blockID",
                FULL_SIGN: "fullSign",
                DROP_OF_ONLY: "dropOffOnly",
                VEHICLE_ID: "vehicleID",
                NEW_TRIP: "newTrip",
                QUERY_TIME: "queryTime",
                PASSENGER_CODE: "passengerCode",
                PIECE: "piece",
                RESULT_SET: "resultSet",
                LOCATION_ID: "locid",
                ERROR_MESSAGE: "errorMessage",
                REASON: "reason",
                DELAYED: "delayed",
                CANCELED: "canceled",
                TRACKING_ERROR: "trackingError",
                TIMESTAMP: "timestamp",
                OFF_ROUTE: "offRoute",
                BLOCK_POSITION: "blockPosition",
                AT: "at",
                ROUTE_NUMBER: "routeNumber",
                SHORT_SIGN_MESSAGE: "signMessage",
                FULL_SIGN_MESSAGE: "signMessageLong",
                NEXT_LOCATION_ID: "nextLocID",
                NEXT_STOP_ID: "nextStopSeq",
                LAST_LOCATION_ID: "lastLocID",
                TRIP: "trip",
                ROUTE_STATUS: "routeStatus",
                PHONETIC: "phonetic",
                IS_DELAYED: "delayed",
                DELAY_MINUTES: "delayMins"
            },
            QUOTES: {
                QUOTE_TEXT: "quote",
                QUOTE_AUTHOR: "author",
                FORISMATIC: {
                    QUOTE_TEXT: "quoteText",
                    QUOTE_AUTHOR: "quoteAuthor"
                }
            },
            FACTS: {
                TEXT: "text",
                NUMBER: "number"
            },
            WEATHER: {
                RESULT_SET: "current_observation",
                WEATHER: "weather",
                CELSIUS_TEMP: "temp_c",
                FAHRENHEIT_TEMP: "temp_f",
                HUMIDITY: "relative_humidity",
                WIND_TEXT: "wind_string",
                WIND_MPH: "wind_mph"
            },
            BART: {
                RESULT_SET: "root",
                MESSAGE: "message",
                HELP: "help",
                URI: "uri",
                STOP: "stop",
                LOAD: "load",
                STATIONS: "stations",
                STATION: "station",
                PARKING_FLAG: "parking_flag",
                BIKE_FLAG: "bike_flag",
                BIKE_STATION_FLAG: "bike_station_flag",
                LOCKER_FLAG: "locker_flag",
                NAME: "name",
                ABBREVIATION: "abbr",
                ENTERING: "entering",
                EXITING: "exiting",
                PARKING: "parking",
                FILL_TIME: "fill_time",
                CAR_SHARE: "car_share",
                LOCKERS: "lockers",
                BIKE_STATION_TEXT: "bike_station_text",
                DESTINATIONS: "destinations",
                DESTINATION: "destination",
                TRANSIT_INFO: "transit_info",
                LINK: "link",
                LEGEND: "legend",
                LATITUDE: "gtfs_latitude",
                LONGIUDE: "gtfs_longitude",
                ADDRESS: "address",
                CITY: "city",
                COUNTRY: "county",
                STATE: "state",
                ZIPCODE: "zipcode",
                NORTH_ROUTES: "north_routes",
                ROUTE: "route",
                SOUTH_ROUTES: "south_routes",
                PLATFORM: "platform",
                NORTH_PLATFORMS: "north_platforms",
                SOUTH_PLATFORMS: "south_platforms",
                PLATFORM_INFO: "platform_info",
                INTRO: "intro",
                CROSS_STREET: "cross_street",
                FOOD: "food",
                SHOPPING: "shopping",
                ATTRACTION: "attraction",
                ORIGIN: "origin",
                ORIG: "orig",
                DEST: "dest",
                SCHEDULE_NUMBER: "sched_num",
                SCHEDULE: "schedule",
                DATE: "date",
                TIME: "time",
                BEFORE: "before",
                AFTER: "after",
                REQUEST: "request",
                TRIP: "trip",
                FARE: "fare",
                ORIGIN_TIME: "origTime",
                ORIGIN_TIME_MIN: "origTimeMin",
                ORIGIN_TIME_DATE: "origTimeDate",
                DESTINATION_TIME_MIN: "destTimeMin",
                DESTINATION_TIME_DATE: "destTimeDate",
                CLIPPER: "clipper",
                DISCOUNT: "discount",
                TRIP_TIME: "tripTime",
                CO2: "co2",
                FARES: "fares",
                LEVEL: "level",
                AMOUNT: "amount",
                CLASS: "class",
                LEG: "leg",
                ORDER: "order",
                TRANSFER_CODE: "transfercode",
                LINE: "line",
                TRAIN: "train",
                TRANI_HEAD_STATION: "trainHeadStation",
                TRAIN_ID: "trainId",
                TRAIN_INDEX: "trainIdx",
                SPECIAL_SCHEDULE: "special_schedule",
                SPECIAL_SCHEDULES: "special_schedules",
                CO2_EMISSIONS: "co2_emissions",
                BIKEFLAG: "bikeflag",
                HOLIDAYS: "holidays",
                HOLIDAY: "holiday",
                SCHEDULE_TYPE: "schedule_type",
                INDEX: "index",
                ID: "id",
                EFFECTIVE_DATE: "effectivedate",
                START_DATE: "start_date",
                END_DATE: "end_date",
                START_TIME: "start_time",
                END_TIME: "end_time",
                TEXT: "text",
                DAY_OF_WEEK: "day_of_week",
                ROUTES_AFFECTED: "routes_affected",
                ABBR: "abbr",
                ITEM: "item",
                ROUTES: "routes",
                NUMBER: "number",
                DIRECTION: "direction",
                DESCRIPTION: "destination",
                COLOR: "color",
                NUMBER_OF_STATIONS: "num_stns",
                CONFIGURATION: "config",
                ETD: "etd",
                ESTIMATE: "estimate",
                LIMITED: "limited",
                MINUTES: "minutes",
                LENGTH: "length",
                HEX_COLOR: "hexcolor",
                BSA: "bsa",
                TYPE: "type",
                SMS_TEXT: "sms_text",
                POSTED: "posted",
                EXPIRES: "expires",
                TRAIN_COUNT: "traincount"
            },
            OBA: {
                RESULT_SET: "response",
                VERSION: "version",
                CODE: "code",
                TEXT: "text",
                CURRENT_TIME: "currentTime",
                DATA: "data",
                REFERENCES: "references",
                AGENCIES: "agencies",
                AGENCY: "agency",
                ROUTES: "routes",
                ROUTE: "route",
                STOPS: "stops",
                STOP: "stop",
                TRIPS: "trips",
                TRIP: "trip",
                SITUATIONS: "situations",
                SITUATION: "situation",
                ID: "id",
                NAME: "name",
                URL: "url",
                TIMEZONE: "timezone",
                LANGUAGE: "lang",
                PHONE: "phone",
                DISCLAIMER: "disclaimer",
                ARRIVAL_AND_DEPARTURE: "arrivalAndDeparture",
                ROUTE_ID: "routeId",
                TRIP_ID: "tripId",
                SERVICE_DATE: "serviceDate",
                STOP_ID: "stopId",
                STOP_SEQUENCE: "stopSequence",
                BLOCK_TRIP_SEQUENCE: "blockTripSequence",
                ROUTE_SHORT_NAME: "routeShortName",
                ROUTE_LONG_NAME: "routeLongName",
                TRIP_HEAD_SIGN: "tripHeadsign",
                ARRIVAL_ENABLED: "arrivalEnabled",
                DEPARTURE_ENABLED: "departureEnabled",
                SCHEDULED_ARRIVAL_TIME: "scheduledArrivalTime",
                SCHEDULED_DEPARTURE_TIME: "scheduledDepartureTime",
                FREQUENCY: "frequency",
                PREDICTED: "predicted",
                PREDICTED_ARRIVAL_TIME: "predictedArrivalTime",
                PREDICTED_DEPARTURE_TIME: "predictedDepartureTime",
                DISTANCE_FROM_STOP: "distanceFromStop",
                NUMBER_OF_STOPS_AWAY: "numberOfStopsAway",
                TRIP_STATUS: "tripStatus",
                START_TIME: "startTime",
                END_TIME: "endTime",
                HEADWAY: "headway",
                SHORT_NAME: "shortName",
                LONG_NAME: "longName",
                DESCRIPTION: "description",
                TYPE: "type",
                COLOR: "color",
                COLOR_TEXT: "textColor",
                AGENCY_ID: "agencyId",
                CREATION_TIME: "creationTime",
                ENVIRONMENTAL_REASON: "environmentReason",
                SUMMARY: "summary",
                VALUE: "value",
                AFFECTS: "affects",
                VEHICLE_JORNEYS: "vehicleJourneys",
                VEHICLE_JOURNEY: "vehicleJourney",
                LINE_ID: "lineId",
                DIRECTION: "direction",
                CALLS: "calls",
                CALL: "call",
                CONSEQUENCES: "consequences",
                CONSEQUENCE: "consequence",
                CONDITION: "condition",
                CONDITION_DETAILS: "conditionDetails",
                DIVERSION_PATH: "diversionPath",
                DIVERSION_STOP_IDS: "diversionStopIds",
                STRING: "string",
                ENTRY: "entry",
                CLASS: "class",
                NEAR_BY_STOP_IDS: "nearbyStopIds",
                SITUATION_IDS: "situationIds",
                POINTS: "points",
                LATITUDE: "lat",
                LONGIUDE: "lon",
                LOCATION_TYPE: "locationType",
                WHEELCHAIR_BOARDING: "wheelchairBoarding",
                ROUTE_IDS: "routeIds",
                STATUS: "status",
                STOP_TIMES: "stopTimes",
                TRIP_STOP_TIME: "tripStopTime",
                ARRIVAL_TIME: "arrivalTime",
                DEPARTURE_TIME: "departureTime",
                PREVIOUS_STOP_ID: "previousTripId",
                NEXT_TRIP_ID: "nextTripId",
                ACTIVE_TRIP_ID: "activeTripId",
                SCHEDULE_DISTANCE_ALONG_TRIP: "scheduledDistanceAlongTrip",
                TOTAL_DISTANCE_ALONG_TRIP: "totalDistanceAlongTrip",
                POSITION: "position",
                ORIENTATION: "orientation",
                CLOSEST_STOP: "closestStop",
                CLOSEST_STOP_TIME_OFFSET: "closestStopTimeOffset",
                NEXT_STOP: "nextStop",
                NEXT_STOP_TIME_OFFSET: "nextStopTimeOffset",
                PHASE: "phase",
                LAST_UPDATE_TIME: "lastUpdateTime",
                LAST_LOCATION_UPDATE_TIME: "lastLocationUpdateTime",
                LAST_KNOWN_LOCATION: "lastKnownLocation",
                LAST_KNOW_ORIENTATION: "lastKnownOrientation",
                DISTANCE_ALONG_TRIP: "distanceAlongTrip",
                SCHEDULED_DEVIATION: "scheduleDeviation",
                VEHICLE_ID: "vehicleId",
                TRIP_SHORT_NAME: "tripShortName",
                SERVICE_ID: "serviceId",
                SHAPEID: "shapeId",
                DIRECTION_ID: "directionId",
                LOCATION: "location",
                VEHICLE_STATUS: "vehicleStatus",
                LIST: "list",
                LIMIT_EXCEEDED: "limitExceeded",
                REFERENCE: "reference",
                ARRIVALS_AND_DEPARTURES : "arrivalsAndDepartures",
                DEPARTURES : "departures",
                ARRIVALS : "arrivals",
                DELAYS : "delays"
            },
            CTA: {
                /** Common Properties */
                LATITUDE: "lat",
                LONGIUDE: "lon",
                NAME: "name",
                MESSAGE: "msg",
                TIME_STAMP: "TimeStamp",
                ERROR_CODE: "ErrorCode",
                ERROR_MESSAGE: "ErrorMessage",
                ROUTE_INFO: "RouteInfo",
                ROUTE_COLOR_CODE: "RouteColorCode",
                ROUTE_COLOR_TEXT: "RouteTextColor",
                SERVICE_ID: "ServiceId",
                ROUTE_URL: "RouteURL",
                BIG_ROUTE: "Route",
                ROUTE_STATUS: "RouteStatus",
                ROUTE_STATUS_COLOR: "RouteStatusColor",
                ROUTE_STATUS_RESULT_SET: "CTARoutes",
                DETAILED_ALERTS_RESULT_SET: "CTAAlerts",
                ALERT: "Alert",
                ALERT_ID: "AlertID",
                HEADLINE: "Headline",
                SHORT_DESCRIPTION: "ShortDescription",
                FULL_DESCRIPTION: "FullDescription",
                SEVERITY_SCORE: "SeverityScore",
                SEVERITY_COLOR: "SeverityColor",
                IMPACT: "Impact",
                EBENT_START: "EventStart",
                EVENT_END: "EventEnd",
                IMPACTED_SERVICE: "ImpactedService",
                SERVICE: "Service",
                SERVICE_TYPE: "ServiceType",
                ALERT_URL: "ServiceType",
                MAJOR_ALERT: "MajorAlert",
                SERVICE_TYPE_DESCRIPTION: "ServiceTypeDescription",
                SERVICE_NAME: "ServiceName",
                SERVICE_BACK_COLOR: "ServiceBackColor",
                SERVICE_TEXT_COLOR: "ServiceTextColor",
                SERVICE_URL: "ServiceURL",

                /** Bus Specific Properties */
                BUS: {
                    RESULT_SET: "bustime-response",
                    ERROR: "error",
                    TIME: 'tm',
                    VEHICLE: "vehicle",
                    VEHICLE_ID: "vid",
                    TIMESTAMP: "tmstmp",
                    VEHICLE_HEADING: "hdg",
                    PATTERN_ID: "pid",
                    PATTERN_DESTINATION: "pdist",
                    CHILD_ROUTE: "rt",
                    DESTINATION: "des",
                    DELAYED: "dly",
                    TA_BLOCK_ID: "tablockid",
                    TA_TRIP_ID: "tatripid",
                    ZONE: "zone",
                    ROUTE: "route",
                    CHILD_ROUTE_NAME: "rtnm",
                    DIRECTION: "dir",
                    STOP: "stop",
                    STOP_ID: "stpid",
                    STOP_NAME: "stpnm",
                    PATTERN: "ptr",
                    CHILD_ROUTE_DIRECTION: "rtdir",
                    POINT: "pt",
                    LENGTH: "ln",
                    SEQUENCE: "seq",
                    TYPE: "typ",
                    PREDICTION: "prd",
                    DISTANCE_TO_STOP: "dstp",
                    PREDICTION_DATE_TIME: "prdtm",
                    PREDICTION_TIME_LEFT: "prdctdn",
                    SERVICE_BULLETING: "Sb",
                    BULLETIN_NAME: "Nm",
                    BULLETING_SUBJECT: "Sbj",
                    BULLETING_DETAILS: "Dtl",
                    BULLETIN_BRIEF: "Brf",
                    BULLETIN_PRIORITY: "Prty",
                    BULLETIN_SERVICE: "Srvc",
                    ROUTE_CHILD_BIG: "Rt",
                    ROUTE_DIRECTION_BIG: "Rtdir",
                    STOP_ID_BIG: "Stpid",
                    STOP_NAME_BIG: "Stpnm",
                },

                /** Train Specific Properties */
                TRAIN: {
                    RESULT_SET: "ctatt",
                    TIMESTAMP: "tmst",
                    ERROR_CODE: "errCd",
                    ERROR_NUMBER: "errNm",
                    ETA: "eta",
                    STATION_ID: "staId",
                    STOP_ID: "stpId",
                    STATION_NAME: "staNm",
                    STOP_DESCRIPTION: "stpDe",
                    RUN_NUMBER: "rn",
                    ROUTE_ABBREVIATION: "rt",
                    DESTINATION_STOP_ID: "destSt",
                    DESTINATION_NAME: "destNm",
                    TRAIN_ROUTE_DIRECTION: "tdDr",
                    PREDICTION_DATE: "prdt",
                    ARRIVAL_TIME: "arrT",
                    IS_APPROACHING: "isApp",
                    IS_SCHEDULED: "isSch",
                    IS_FAULTY: "isFlt",
                    IS_DELAYED: "isDly",
                    FLAGS: "flags",
                    HEADING: "heading",
                    TRAIN: "train",
                }
            }
        }
    },

    /** Application API, Transit Providers code */
    PROVIDERS: {
        TRIMET: "TRIMET",
        BART: "BART",
        GOOGLE: "GOOGLE",
        CTA: "CTA",
        MTA: "MTA",
        OBA: "OBA"
    },

    /** Global Application Settings */
    APP: {
        ZIPCODE_SETUP_LIMIT: "ZIPCODE_SETUP_LIMIT",
        TERMINATE: "TERMINATE",
        PROVIDER_CODE: "PROVIDER_CODE",
        PROVIDER_DESCRIPTION: "DESCRIPTION",
        AGENCY_CODE: "AGENCY_CODE",
        /** Pagination Constants */
        TOTAL_PAGES: "TOTAL_PAGES",
        CURRENT_PAGE: "CURRENT_PAGE",
        TOATL_RECORDS: "TOATL_RECORDS",
        RECORDS_SET: "RECORDS_SET",
        LAST_INDEX: "LAST_INDEX",
        ITEM_COUNT: "ITEM_COUNT"
    },

    /** Alexa Related Settings Names */
    ALEXA: {
        APP_ID: "APP_ID",
        SESSION_DYNAMODB_TABLE_NAME: "SESSION_DYNAMODB_TABLE_NAME",
        APP_DYNAMODB_TABLE_NAME: "APP_DYNAMODB_TABLE_NAME",
        REQUEST_TYPE: {
            LAUNCH_REQUEST: "LaunchRequest",
            INTENT_REQUEST: "IntentRequest"
        }
    },

    /** Attributes for Session management */
    ATTRIBUTES: {
        STATE: "STATE",
        LAST_STOP_ID: "LAST_STOP_ID",
        LAST_ROUTE_ID: "LAST_ROUTE_ID",
        LAST_BUS_ID: "LAST_BUS_ID",
        STOP_ID: "STOP_ID",
        STATION_ID: "STATION_ID",
        ZIPCODE: "ZIPCODE",
        ROUTE_ID: "ROUTE_ID",
        BUS_ID: "BUS_ID",
        CITY: "CITY",
        COUNTRY: "COUNTRY",
        SERVICE_NAME: "SERVICE_NAME",
        AGENCY_ID: "AGENCY_ID",
        FAVOURATE_STOPS: "FAVOURATE_STOPS",
        FAVOURATE_STOP_NAMES: "FAVOURATE_STOP_NAMES",
        FAVOURATE_ROUTES: "FAVOURATE_ROUTES",
        FAVOURATE_BUSES: "FAVOURATE_BUSES",
        SPEECH_OUTPUT: "SPEECH_OUTPUT",
        PROPMT_OUTPUT: "PROPMT_OUTPUT",
        SETUP_ATTEMPTS: "SETUP_ATTEMPTS",
        SETUP_LIMIT: "SETUP_LIMIT",
        CONTEXT: "CONTEXT",
        TIMEZONE: "TIMEZONE",
        UTC: "UTC",
        LATITUDE: "LATITUDE",
        LONGIUDE: "LONGIUDE",
        FOUND_ADDRESS: "FOUND_ADDRESS",
        COUNTRY_STATE: "COUNTRY_STATE",
        AVAILABLE_STOPS: "AVAILABLE_STOPS",
        CURRENT_STOP: "CURRENT_STOP",
        NEXT_STOP: "NEXT_STOP",
        CURRENT_STOP_INDEX: "CURRENT_STOP_INDEX",
        LAST_STOP_INDEX: "LAST_STOP_INDEX",
        FIRST_STOP_INDEX: "FIRST_STOP_INDEX",
        LAST_STOP_NAME: "LAST_STOP_NAME",
        RANDOM_QUOTE: "RANDOM_QUOTE",
        RANDOM_FACT: "RANDOM_FACT",
        WEATHER_FORCAST: "WEATHER_FORCAST",
        PROVIDED_STOP_DETAILS: "PROVIDED_STOP_DETAILS",
        FOUND_COUNTRY: "FOUND_COUNTRY",
        FOUND_STOP_DETAILS: "FOUND_STOP_DETAILS",
        TRIES_LEFT: "TRIES_LEFT",
        HOME_STOP_NAME: "HOME_STOP_NAME",
        REQUESTED_STOP_ID: "REQUESTED_STOP_ID",
        REQUESTED_BUS_ID: "REQUESTED_BUS_ID",
        REQUESTED_ROUTE_ID: "REQUESTED_ROUTE_ID",
        REQUESTED_STOP_NAME: "REQUESTED_STOP_NAME",
        /** Navigation Attributes */
        ITEMS_COLLECTION: "ITEMS_COLLECTION",
        CURRENT_ITEM_INDEX: "CURRENT_ITEM_INDEX",
        LAST_ITEM_INDEX: "LAST_ITEM_INDEX",
        FIRST_ITEM_INDEX: "FIRST_ITEM_INDEX",
        CURRENT_ITEM: "CURRENT_ITEM",
        SETUP_ID_TYPE: "SETUP_ID_TYPE",
        SERVICE_CODE: "SERVICE_CODE",
        NEXT_ITEM_INDEX: "NEXT_ITEM_INDEX",
        PREVIOUS_ITEM_INDEX: "PREVIOUS_ITEM_INDEX",
        SETUP_TYPE: "SETUP_TYPE",
        /** Paging */
        PAGE_SIZE: "PAGE_SIZE",
        TOTAL_PAGES: "TOTAL_PAGES",
        CURRENT_PAGE: "CURRENT_PAGE",
        TOTAL_RECORDS: "TOTAL_RECORDS",
        CURRENT_RECORD: "CURRENT_RECORD",
        LOCALE: "LOCALE"
    },

    DEFAULTS: {
        "OK_EXCLAMATION": "DEFAULT_OK_EXCLAMATION",
        "SORRY_EXCLAMATION": "DEFAULT_SORRY_EXCLAMATION",
        "HELP_PROMPT": "DEFAULT_HELP_MESSAGE",
        "GOODBYE_MESSAGE": "DEFAULT_GOODBYE_MESSAGE",
        "WELCOME_EXCLAMATION": "DEFAULT_WELCOME_EXCLAMATION",
        DATE_FORMAT: "YYYYMMDD",
        TIME_FORMAT: "hh:mm a",
        SHORT_DATE_FORMAT: "dddd, MMMM Do, YYYY",
        LOCALE: "en-US",
        COUNTRY : "United States",
        TIMEZONE : "America/Los_Angeles"
    },

    /** Enumeration of Types */
    ENUM: {
        HOLIDAYS: {
            'NEW_YEAR': "New Year's",
            'INAUGURATION': "Inauguration",
            'MARTIN_LUTHER_KING': "Martin Luther King Jnr.",
            'GEORGE_WASHINGTON': "George Washington",
            'MEMORIAL': "Memorial",
            'INDEPENDENCE': "Independence",
            'LABOR': "Labor",
            'COLUMBUS': "Columbus",
            'VETERANS': "Veterans",
            'THANKS_GIVING': "Thanksgiving",
            'CHRISTMAS': "Christmas",
            'PRESIDENTS': "Presidents",
            'EMANCIPATION': "Emancipation",
            'MOTHERS': "Mother's",
            'FATHERS': "Father's",
            'HALLOWEEN': "Halloween"
        },
        ADJECTIVES: {
            REF: "ADJECTIVES",
            POSITIVE: "POSITIVE",
            NEGATIVE: "NEGATIVE",
            HOLIDAYS: "HOLIDAYS"
        },
        PHRASES: {
            REF: "PHRASES",
            FACTS_INTRO: "FACTS_INTRO",
            GOOD_BYE: "GOOD_BYE",
            THANK_YOU: "THANK_YOU"
        },
        GREETINGS: {
            REF: "GREETINGS",
            MORNING: "MORNING",
            AFTERNOON: "AFTERNOON",
            EVENING: "EVENING",
            NIGHT: "NIGHT",
            DEFAULT: "DEFAULT_GREETING"
        },
        NAVIGATION: {
            NEXT: "NEXT",
            PREVIOUS: "PREVIOUS"
        },
        REQUEST_TYPE: {
            HOME: "HOME",
            OTHER: "OTHER"
        },
        SETUP_ID_TYPE: {
            STATION: "STATION",
            STOP: "STOP"
        },
        SETUP_TYPE: {
            ZIPCODE: "ZIPCODE",
            STOP_STATION_ID: "STOP_STATION_ID"
        },
        TRIMET: {
            PASSENGER_CODE: {
                E: "Either boarding or alighting",
                A: "Alighting only",
                B: "Boarding only",
                N: "Neither boarding nor alighting"
            },
            ROUTE_TYPE: {
                B: "Bus",
                R: "Train"
            }
        },
        DEBUG: {
            TYPE: {
                JSON: "JSON",
                TEXT: "TEXT"
            }
        },
        SSML: {
            SPEAK_AS: {
                CARDINAL: "cardinal",
                DIGITS: "digits",
                SPELL_OUT: "spell-out",
                CHARACTERS: "characters",
                NUMBERS: "number",
                ORDINAL: "ordinal",
                FRACTION: "fraction",
                UNIT: "unit",
                DATE: "date",
                DATE_FORMAT: {
                    MDY: "mdy",
                    DMY: "dmy",
                    YMD: "ymd",
                    MD: "md",
                    DM: "dm",
                    YM: "ym",
                    MY: "my",
                    D: "d",
                    M: "m",
                    Y: "y"
                },
                TIME: "time",
                TELEPHONE: "telephone",
                ADDRESS: "address"
            }
        },
        BART: {
            API_DATES: {
                TODAY: "today",
                NOW: "now",
                WEEKDAY: "wd",
                SATURDAY: "sa",
                SUNDAY: "su"
            },
            API_CMD: {
                REAL_TIME_ARRIVALS: "etd",
                HELP: "help",
                STATION_ACCESS: "stnaccess",
                ORIGIN_STATION: "orig",
                STATION_INFO: "stninfo",
                STATIONS: "stns",
                STATION_SCHEDULE: "stnsched",
                SPECIAL_SCHEDULE: "special",
                CURRENT_SCHEDULES: "scheds",
                ROUTE_SCHEDULE: "routesched",
                HOLIDAY_SCHEDULE: "holiday",
                FARE: "fare",
                DEPARTING_SCHEDULE: "depart",
                ARRIVING_SCHEDULE: "arrive",
                ROUTE_INFO: "routeinfo",
                ROUTES: "routes",
                SERVICE_ADVISORY: "bsa",
                TRAIN_COUNT: "count",
                ELEVATOR_ALERTS: "elev"
            },
            API_CLASS: {
                CASH: "cash",
                RTCCLIPPERS: "rtcclipper"
            },
            LEGENDS: {
                BIKE_FLAG: {
                    "0": "No bike racks",
                    "1": "Yes, bike racks available"
                },
                TRANSFER_CODE: {
                    "": "no transfer",
                    "N": "normal transfer",
                    "T": "timed transfer, connecting trains will wait up to five minutes for transferring passengers.",
                    "S": "scheduled transfer, connecting trains will not wait for transferring passengers if there is a delay."
                },
                PARKING_FLAG: {
                    "0": "No BART parking",
                    "1": "Yes, parking available"
                },
                BIKE_STATION_FLAG: {
                    "0": "Not a bike station",
                    "1": "Yes, station is a bike station"
                },
                LOCKER_FLAG: {
                    "0": "No lockers",
                    "1": "Yes, station has lockers"
                },
                BIKEFLAG: {
                    "0": "no bikes allowed",
                    "1": "bikes allowed"
                },
                DAY_OF_WEEK: {
                    "": "All Days",
                    "0": "sunday",
                    "1": "Monday",
                    "2": "Tuesday",
                    "3": "Wednesday",
                    "4": "Thursday",
                    "5": "Friday",
                    "6": "Saturday"
                }
            }
        },
        OBA: {
            API_METHODS: {
                AGENCIES_WITH_COVERAGE: "agencies-with-coverage.json?",
                STOPS_FOR_LOCATION: "stops-for-location.json?",
                ROUTES_FOR_LOCATION: "routes-for-location.json?",
                ARRIVALS_AND_DEPARTURES: "arrivals-and-departures-for-stop/",
                SCHEDULE_FOR_STOP: "schedule-for-stop/",
                STOPS_FOR_ROUTE: "stops-for-route/",
                STOP_INFO: "stop/",
                VEHICLES_FOR_AGENCY: "vehicles-for-agency/"
            },
            SERVICE_ADVISORY : {
                DIRECTION : {
                    "EB" : "Eastbound",
                    "IB" : "Inbound",
                    "NB" : "Northbound",
                    "OB" : "Outbound",
                    "SB" : "Southbound",
                    "WB" : "Westbound"
                },
                ROUTING_TURNS : {
                    "C" : "Continue",
                    "L" : "Left",
                    "R" : "Right"
                },
                STOP_ORIENTATION : {
                    "AT" : "At",
                    "FM" : "Far Side, Mid block",
                    "FS" : "Far side, just after the intersection",
                    "NM" : "Near side, Mid block",
                    "NS" : "Near side, Just before the intersection",
                    "OP" : "Opposite"
                }
            }
        },
        CTA: {
            API_METHODS: {
                VEHICLES: "getvehicles",
                SERVER_TIME: "gettime",
                ROUTES: "getroutes",
                ROUTE_DIRECTIONS: "getdirections",
                STOPS: "getstops",
                PREDICTIONS: "getpredictions",
                SERVICE_BULLETING: "getservicebulletins"
            },
            SERVICE_TYPES: {
                "X": "Systemwide",
                "R": "Train Service",
                "B": "Bus Service",
                "T": "Train Station"
            }
        }
    }

    /** TODO: ADD HTTP Request Status */
});